# -*- coding: utf-8 -*-
"""classification_2 的副本

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vB50_EP6ckx-yHBu7RlGEUHtwIDencAk
"""

'''
利用新業配資料之分類
'''

import json
import torch
import pandas as pd
import numpy as np
from transformers import AutoTokenizer, AutoModel
from tqdm import tqdm
from sklearn.model_selection import StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score, f1_score, accuracy_score, classification_report

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

# SMOTE
from imblearn.pipeline import make_pipeline as make_imb_pipeline
from imblearn.over_sampling import SMOTE

"""# 合併資料與特徵建立（含基底模型）"""

df1 = pd.read_csv("/content/data.csv", encoding='utf-8-sig')
df2 = pd.read_csv("/content/sentiment_results_upgraded.csv", encoding='utf-8-sig')
df3 = pd.read_csv("/content/業配文標記.csv", encoding='utf-8-sig')
df4 = pd.read_csv("/content/new_labeling.csv", encoding='utf-8-sig')
df5 = pd.read_csv("/content/dcard_name.csv", encoding='utf-8')


with open('/content/id_mapping_name.json', 'r', encoding='utf-8') as file:
    mapping_dict = json.load(file)

#print(df1)
#print(df2.head())
#print(df3.head())

# =====================================
# 資料合併
# =====================================
# 將最新標記業配文與內文合併
df4 = pd.merge(df4, df5, on='id', how='left')

# 將 JSON 轉換為 DataFrame，並確保 id 的型態與主表一致
# 由於 JSON 的 Key 預設是字串，轉換時需將其轉為與 df1['id'] 相同的型態（通常是 int64 或轉換成一致）
df_mapping = pd.DataFrame(list(mapping_dict.items()), columns=['id', 'file_number'])
df_mapping['id'] = df_mapping['id'].astype(int)            # 轉成數字以利與 df1, df3 合併
df_mapping['file_number'] = df_mapping['file_number'].astype(str) # 轉成字串以利與 df2 對接

# 處理 df2 (sentiment)，將 "1.txt" 轉換成純數字 "1"
df2['file_number'] = df2['file_name'].str.replace('.txt', '', regex=False).astype(str)

# 將情感分析結果 (df2) 與對照表 (df_mapping) 合併，取得文章的真實 id
df_sentiment_mapped = pd.merge(df_mapping, df2, on='file_number', how='inner')
# 移除過渡用的欄位，只保留 id 與情感分析特徵
df_sentiment_mapped = df_sentiment_mapped.drop(columns=['file_number', 'file_name'])

# 處理 df3 與 df4 (業配文標記)：保留特定欄位
keep_cols = ['id', 'title', 'content', '最終判定']
df3_subset = df3[keep_cols] if all(col in df3.columns for col in keep_cols) else df3
df4_subset = df4[keep_cols] if all(col in df4.columns for col in keep_cols) else df4
df3_subset = pd.concat([df3_subset, df4_subset], axis=0, ignore_index=True)

# 以 df1 為核心，依據 'id' 進行全面合併 (Left Join)
# 這樣可以確保主表的資料完整，即使某些文章沒有情感分析或標記也能保留
final_df = pd.merge(df1, df3_subset, on='id', how='left')
final_df = pd.merge(final_df, df_sentiment_mapped, on='id', how='left')

# 去除過程造成的重複資料
final_df = final_df.drop_duplicates(subset='id')

# 合併結果
print(f"資料筆數：{final_df.shape[0]} ，欄位數：{final_df.shape[1]} ")
#print(final_df.head())

#final_df.to_csv("/content/merged_dataset.csv", index=False, encoding='utf-8-sig')

# =====================================
# 特徵建立：關鍵字頻率
# =====================================

# 1. 定義分類關鍵詞字典（英文統一用小寫）
category_keywords = {
    "cta_click": [
        "點我下單", "輸入代碼", "傳送門", "官方網站", "粉絲專頁", "粉專",
        "點入官網", "直接點這裡", "詳細資訊請見", "私訊", "留言", "加好友",
        "追蹤", "分享", "收藏", "報名", "預約", "下載", "填寫", "按讚"
    ],
    "promotion": [
        "讀者優惠", "折扣", "專屬優惠", "優惠碼", "限時團購", "開團",
        "團購價", "買一送一", "免費", "免運", "划算", "cp值", "省錢",
        "便宜", "下殺", "滿額", "福利", "附贈", "折價券", "優惠券"
    ],
    "urgency": [
        "手刀", "值得", "值回票價", "佛心", "誠意滿滿", "一定要試試",
        "必買", "必去", "必吃", "推推", "大推", "超推", "首選",
        "不來可惜", "趁現在", "回購", "必囤", "囤貨", "種草", "激推", "強推"
    ],
    "disclosure": [
        "感謝邀請", "合作邀約", "體驗文", "商業合作", "產品贊助",
        "sponsored", "ad", "pr", "愛體驗", "試用分享", "活動體驗"
    ],
    "platform_brand": [
        "kkday", "klook", "客路", "agoda", "booking.com", "travago",
        "tripadvisor", "網卡", "wifi機", "機加酒", "旅遊平安險",
        "新安東京", "富邦", "雄獅旅遊", "可樂旅遊", "東南旅遊",
        "五福旅遊", "易遊網", "蝦皮", "momo", "淘寶", "官網"
    ],
    "recommendation": [
        "真心推薦", "私心推薦", "真心"
    ],
    "lottery": [ # 獨立拆分出抽獎類，因為抽獎通常帶有高互動與商業增粉性質
        "抽獎", "文末抽獎", "留言抽獎"
    ]
}

# 2. 合併標題與內文並轉小寫，處理空值
full_text = (final_df['title'].fillna('') + " " + final_df['content'].fillna('')).str.lower()

# 3. 處理總字數，避免除以 0
word_counts = final_df['wordCount'].fillna(0).replace(0, 1)


# 4. 依照類別進行計算
for category, kw_list in category_keywords.items():
    # 去除重複字詞並確保小寫
    cleaned_kws = list(set([kw.lower() for kw in kw_list]))

    # 陣列：加總該類別下所有詞彙的出現次數
    total_counts_for_cat = np.zeros(len(final_df))

    for kw in cleaned_kws:
        # 累加每個詞彙出現的次數
        total_counts_for_cat += full_text.str.count(kw).values

    # 計算該類別的總體頻率： 類別總次數 / 文章總字數
    final_df[f"cat_freq_{category}"] = total_counts_for_cat / word_counts


# 5. 結果
#feature_cols = [f"cat_freq_{cat}" for cat in category_keywords.keys()]
#print(final_df[['id', 'wordCount'] + feature_cols].head())

# final_df.to_csv("/content/dataset_with_category_features.csv", index=False, encoding='utf-8-sig')

# =====================================================================
# 根據內文、標題產生業配文機率
# =====================================================================

# 1. 處理標籤（T/F）的資料
labeled_df = final_df[final_df['最終判定'].isin(['T', 'F', 1])].copy().reset_index(drop=True)

labeled_df['label'] = labeled_df['最終判定'].map({'T': 1, 'F': 0, 1: 1})

labeled_df['title'] = labeled_df['title'].fillna('')
labeled_df['content'] = labeled_df['content'].fillna('')
y = labeled_df['label'].values

# 2. BERT 分詞取得標題與內文的 CLS 向量
model_name = "ckiplab/bert-base-chinese"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)
model.eval()

def extract_bert_in_batches(text_list, max_len, desc_text):
    embeddings = []
    for i in tqdm(range(0, len(text_list), 16), desc=desc_text):
        batch_texts = text_list[i:i+16]
        inputs = tokenizer(batch_texts, padding=True, truncation=True, max_length=max_len, return_tensors="pt")
        inputs = {k: v.to(device) for k, v in inputs.items()}
        with torch.no_grad():
            outputs = model(**inputs)
            cls_vectors = outputs.last_hidden_state[:, 0, :].cpu().numpy()
            embeddings.append(cls_vectors)
    return np.vstack(embeddings)

print("--- 正在提取【標題 (Title)】的 BERT 特徵 ---")
X_bert_title = extract_bert_in_batches(labeled_df['title'].tolist(), max_len=64, desc_text="標題特徵")

print("\n--- 正在提取【內文 (Content)】的 BERT 特徵 ---")
X_bert_content = extract_bert_in_batches(labeled_df['content'].tolist(), max_len=512, desc_text="內文特徵")

# =====================================================================
# 3. 定義欲測試的候選模型
# =====================================================================
# 注意：SVM 必須設定 probability=True 才能輸出第二階段需要的機率特徵
candidate_models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, C=0.1, random_state=42),
    "Linear SVM": SVC(kernel='linear', C=0.1, probability=True, random_state=42),
    "RBF SVM (Non-linear)": SVC(kernel='rbf', C=1.0, probability=True, random_state=42)
}

# =====================================================================
# 4. 交叉驗證評估各模型效果
# =====================================================================
n_splits = 5
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# 用來存儲每個模型在 Out-of-Fold 盲測下的預測結果與表現指標
model_performance = {}
model_oof_probs = {} # 記錄各模型算出的機率

for model_name, clf in candidate_models.items():
    print(f"\n======== 評估文字模型：{model_name} ========")

    # 存放當前模型盲測機率的陣列
    oof_title_p = np.zeros(len(labeled_df))
    oof_content_p = np.zeros(len(labeled_df))

    for fold, (train_idx, val_idx) in enumerate(skf.split(X_bert_title, y)):
        y_train, y_val = y[train_idx], y[val_idx]

        # --- 4.1 標題模型訓練與預測 ---
        X_tr_title, X_va_title = X_bert_title[train_idx], X_bert_title[val_idx]
        scaler_t = StandardScaler()
        X_tr_title_sc = scaler_t.fit_transform(X_tr_title)
        X_va_title_sc = scaler_t.transform(X_va_title)

        # 複製一份全新未訓練的模型
        clf_title = torch.hub.load('meta-llama/Llama-2-7b-hf', 'dummy', source='local') if False else type(clf)(**clf.get_params())
        clf_title.fit(X_tr_title_sc, y_train)
        oof_title_p[val_idx] = clf_title.predict_proba(X_va_title_sc)[:, 1]

        # --- 4.2 內文模型訓練與預測 ---
        X_tr_content, X_va_content = X_bert_content[train_idx], X_bert_content[val_idx]
        scaler_c = StandardScaler()
        X_tr_content_sc = scaler_c.fit_transform(X_tr_content)
        X_va_content_sc = scaler_c.transform(X_va_content)

        clf_content = type(clf)(**clf.get_params())
        clf_content.fit(X_tr_content_sc, y_train)
        oof_content_p[val_idx] = clf_content.predict_proba(X_va_content_sc)[:, 1]

    # 模型型成效指標 (以 AUC 為主)
    title_auc = roc_auc_score(y, oof_title_p)
    content_auc = roc_auc_score(y, oof_content_p)

    # 將預測概率 > 0.5 定義為預測業配文 （計算 F1-score）
    title_f1 = f1_score(y, (oof_title_p > 0.5).astype(int))
    content_f1 = f1_score(y, (oof_content_p > 0.5).astype(int))

    model_performance[model_name] = {
        "Title AUC": title_auc, "Title F1": title_f1,
        "Content AUC": content_auc, "Content F1": content_f1
    }

    # 儲存機率，以利後續選擇效果最佳之模型
    model_oof_probs[model_name] = (oof_title_p, oof_content_p)

# =====================================================================
# 5. 輸出模型對比報告
# =====================================================================
print("\n================== 文字模型成效 ==================")
perf_df = pd.DataFrame(model_performance).T
print(perf_df.round(4))

# =====================================================================
# 6. 標題與內文各自挑選表現最佳的模型
# =====================================================================
# 6.1 根據 'Title AUC' 自動找出標題表現最好的模型名稱
best_title_model_name = perf_df['Title AUC'].idxmax()
# 6.2 根據 'Content AUC' 自動找出內文表現最好的模型名稱
best_content_model_name = perf_df['Content AUC'].idxmax()

print(f" 標題特徵 (Title) 最佳模型：【{best_title_model_name}】，其 AUC 為 {perf_df.loc[best_title_model_name, 'Title AUC']:.4f}")
print(f" 內文特徵 (Content) 最佳模型：【{best_content_model_name}】，其 AUC 為 {perf_df.loc[best_content_model_name, 'Content AUC']:.4f}")

# 6.3 提取標題最佳模型的 Out-of-Fold 預測機率
# model_oof_probs[模型名稱] 的格式為 (title_prob, content_prob)
best_title_prob = model_oof_probs[best_title_model_name][0]

# 6.4 提取內文最佳模型的 Out-of-Fold 預測機率
best_content_prob = model_oof_probs[best_content_model_name][1]

# 6.5 塞回 DataFrame，作為第二階段分類特徵
labeled_df['title_is_ad_prob'] = best_title_prob
labeled_df['content_is_ad_prob'] = best_content_prob

# 儲存CSV
labeled_df.to_csv("/content/optimized_local_bert_meta_dataset.csv", index=False, encoding='utf-8-sig')

"""# 若已完成基底模型，可不跑上面，直接讀取資料做以下分析"""

labeled_df= pd.read_csv("/content/optimized_local_bert_meta_dataset.csv", encoding='utf-8-sig')

#print(labeled_df.columns)
print(labeled_df.shape)

"""## stacking"""

# =====================================================================
# 特徵整合
# =====================================================================
exclude_cols = ['id', 'title', 'content', '最終判定', 'label']
numerical_features = [col for col in labeled_df.columns if col not in exclude_cols]

X_meta = labeled_df[numerical_features].copy()
y = labeled_df['label'].values

print(f"最終輸入特徵總數：{X_meta.shape[1]}")

# =====================================================================
# 第二階段模型
# =====================================================================
global_pos_weight = (len(y) - sum(y)) / sum(y)

# for Logistic Regression and RandomForest
def create_safe_pipeline(base_model):
    return make_pipeline(
        SimpleImputer(strategy='median'), # 遇到 NaN 自動填補中位數
        StandardScaler(),                 # 消除尺度差異
        base_model
    )


meta_models = {
    # Logistic Regression：填補 + 標準化
    "Logistic Regression (Meta)": create_safe_pipeline(
        LogisticRegression(max_iter=1000, C=1.0, random_state=42)
    ),

    # RandomForest：填補
    "Random Forest (Meta)": create_safe_pipeline(
        RandomForestClassifier(n_estimators=100, max_depth=6, class_weight='balanced', random_state=42)
    ),

    # RandomForest（參數調整）
    "Random Forest (class_weight=balanced_subsample)": create_safe_pipeline(
        RandomForestClassifier(n_estimators=100, max_depth=6, class_weight='balanced_subsample', random_state=42)
    ),

    # XGBoost
    "XGBoost (Meta)": XGBClassifier(
        n_estimators=120, max_depth=5, learning_rate=0.05,
        scale_pos_weight=global_pos_weight, random_state=42, eval_metric='logloss'
    ),

    # LightGBM
    "LightGBM (Meta)": LGBMClassifier(
        n_estimators=120, max_depth=5, learning_rate=0.05,
        scale_pos_weight=global_pos_weight, random_state=42, verbosity=-1
    ),

    # LightGBM（參數調整）
    "LightGBM (is_unbalanceTrue)": LGBMClassifier(
        n_estimators=120, max_depth=5, learning_rate=0.05,
        random_state=42, verbosity=-1,is_unbalance=True
    )
}

# =====================================================================
# K-fold
# =====================================================================
n_splits = 5
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

meta_performance = {}
meta_oof_probs = {}

for model_name, model_instance in meta_models.items():

    oof_preds = np.zeros(len(labeled_df))
    oof_probs = np.zeros(len(labeled_df))

    for fold, (train_idx, val_idx) in enumerate(skf.split(X_meta, y)):
        X_train_meta, y_train = X_meta.iloc[train_idx], y[train_idx]
        X_val_meta, y_val = X_meta.iloc[val_idx], y[val_idx]

        from sklearn.base import clone
        clf = clone(model_instance)

        clf.fit(X_train_meta, y_train)

        oof_preds[val_idx] = clf.predict(X_val_meta)
        oof_probs[val_idx] = clf.predict_proba(X_val_meta)[:, 1]

    # 計算指標
    acc = accuracy_score(y, oof_preds)
    f1 = f1_score(y, oof_preds)
    auc = roc_auc_score(y, oof_probs)

    meta_performance[model_name] = {"Accuracy": acc, "F1-Score": f1, "AUC": auc}
    meta_oof_probs[model_name] = oof_probs

    print(f"--- {model_name}  ---")
    print(classification_report(y, oof_preds, target_names=['非業配 (F)', '業配文 (T)'], digits=3))

# =====================================================================
# 最終模型報告
# =====================================================================
print("\n=========================================================")
print("========= 第二階段模型 (Meta-Learner) 成效 =========")
print("=========================================================")
perf_df = pd.DataFrame(meta_performance).T
print(perf_df.round(4))
print("=========================================================")

best_meta_model_name = perf_df['AUC'].idxmax()
print(f"\n 實驗結論：推薦使用【{best_meta_model_name}】")

# 預測結果
final_df = labeled_df.copy()
final_df['final_prediction_prob'] = meta_oof_probs[best_meta_model_name]
# labeled_df.to_csv("/content/final_multi_model_meta_dataset.csv", index=False, encoding='utf-8-sig')

# =====================================================================
# 選取 threshold
# =====================================================================

final_df['final_prediction_prob'] = meta_oof_probs[best_meta_model_name]
actual_label = final_df['label']

for threshold in [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]:
    final_df['final_prediction_label'] = (meta_oof_probs[best_meta_model_name] > threshold).astype(int)
    print(f"\nthreshold : {threshold} ")

    cross_tab = pd.crosstab(
        actual_label,
        final_df['final_prediction_label'],
        rownames=['Actual'],
        colnames=['Predicted']
    )
    print("===== confusion matrix =====")
    print(cross_tab)


    print("================== report ===================")
    print(classification_report(
        actual_label,
        final_df['final_prediction_label'],
        target_names=['非業配 (F)', '業配文 (T)'],
        digits=3
    ))

"""## SMOTE"""

exclude_cols = ['id', 'title', 'content', '最終判定', 'label']
numerical_features = [col for col in labeled_df.columns if col not in exclude_cols]

X_meta = labeled_df[numerical_features].copy()
y = labeled_df['label'].values

print(f"最終第二階段模型輸入特徵總數：{X_meta.shape[1]} ")


def create_smote_pipeline(base_model, need_scale=False):

    steps = [
        SimpleImputer(strategy='median'),
        SMOTE(sampling_strategy='auto', random_state=42) # 自動平衡少數派
    ]
    if need_scale:
        steps.append(StandardScaler())
    steps.append(base_model)


    return make_imb_pipeline(*steps)

meta_models = {
    "Logistic Regression + SMOTE": create_smote_pipeline(
        LogisticRegression(max_iter=1000, C=1.0, random_state=42), need_scale=True
    ),

    "Random Forest + SMOTE": create_smote_pipeline(
        RandomForestClassifier(n_estimators=100, max_depth=6, random_state=42), need_scale=False
    ),

    "XGBoost + SMOTE": create_smote_pipeline(
        XGBClassifier(n_estimators=120, max_depth=5, learning_rate=0.05, random_state=42, eval_metric='logloss'), need_scale=False
    ),

    "LightGBM + SMOTE": create_smote_pipeline(
        LGBMClassifier(n_estimators=120, max_depth=5, learning_rate=0.05, random_state=42, verbosity=-1), need_scale=False
    )
}

# =====================================================================
# K-fold
# =====================================================================
n_splits = 5
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

meta_performance = {}
meta_oof_probs = {}

for model_name, model_instance in meta_models.items():

    oof_preds = np.zeros(len(labeled_df))
    oof_probs = np.zeros(len(labeled_df))

    for fold, (train_idx, val_idx) in enumerate(skf.split(X_meta, y)):
        X_train_meta, y_train = X_meta.iloc[train_idx], y[train_idx]
        X_val_meta, y_val = X_meta.iloc[val_idx], y[val_idx]

        from sklearn.base import clone
        clf = clone(model_instance)

        clf.fit(X_train_meta, y_train)

        oof_preds[val_idx] = clf.predict(X_val_meta)
        oof_probs[val_idx] = clf.predict_proba(X_val_meta)[:, 1]

    # 計算指標
    acc = accuracy_score(y, oof_preds)
    f1 = f1_score(y, oof_preds)
    auc = roc_auc_score(y, oof_probs)

    meta_performance[model_name] = {"Accuracy": acc, "F1-Score": f1, "AUC": auc}
    meta_oof_probs[model_name] = oof_probs

    print(f"--- {model_name} 詳細報告 ---")
    print(classification_report(y, oof_preds, target_names=['非業配 (F)', '業配文 (T)'], digits=3))

# =====================================================================
# 輸出最終模型報告
# =====================================================================
print("\n=========================================================")
print("=============== SMOTE 後第二階段模型成效對比 ===============")
print("=========================================================")
perf_df = pd.DataFrame(meta_performance).T
print(perf_df.round(4))
print("=========================================================")

best_meta_model_name = perf_df['AUC'].idxmax()
print(f"\n 推薦使用【{best_meta_model_name}】作為最終的業配文決策模型")

"""## ROS"""

from sklearn.base import clone
from imblearn.over_sampling import RandomOverSampler
import warnings
warnings.filterwarnings('ignore', category=UserWarning)

exclude_cols = ['id', 'title', 'content', '最終判定', 'label']
numerical_features = [col for col in labeled_df.columns if col not in exclude_cols]

X_meta = labeled_df[numerical_features].copy()
y = labeled_df['label'].values

print(f"最終第二階段模型輸入特徵總數：{X_meta.shape[1]} ")

# 2. 修改 Pipeline 建立函數，將 SMOTE 換成 RandomOverSampler
def create_ros_pipeline(base_model, need_scale=False):
    steps = [
        SimpleImputer(strategy='median'),
        RandomOverSampler(sampling_strategy='auto', random_state=42) # 改用隨機過採樣
    ]
    if need_scale:
        steps.append(StandardScaler())
    steps.append(base_model)

    return make_imb_pipeline(*steps)

# 3. 更新模型字典名稱與呼叫的函數
meta_models = {
    "Logistic Regression + ROS": create_ros_pipeline(
        LogisticRegression(max_iter=1000, C=1.0, random_state=42), need_scale=True
    ),

    "Random Forest + ROS": create_ros_pipeline(
        RandomForestClassifier(n_estimators=100, max_depth=6, random_state=42), need_scale=False
    ),

    "XGBoost + ROS": create_ros_pipeline(
        XGBClassifier(n_estimators=120, max_depth=5, learning_rate=0.05, random_state=42, eval_metric='logloss'), need_scale=False
    ),

    "LightGBM + ROS": create_ros_pipeline(
        LGBMClassifier(n_estimators=120, max_depth=5, learning_rate=0.05, random_state=42, verbosity=-1), need_scale=False
    )
}

# =====================================================================
# K-fold
# =====================================================================
n_splits = 5
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

meta_performance = {}
meta_oof_probs = {}

for model_name, model_instance in meta_models.items():

    oof_preds = np.zeros(len(labeled_df))
    oof_probs = np.zeros(len(labeled_df))

    for fold, (train_idx, val_idx) in enumerate(skf.split(X_meta, y)):
        X_train_meta, y_train = X_meta.iloc[train_idx].values, y[train_idx]
        X_val_meta, y_val = X_meta.iloc[val_idx].values, y[val_idx]

        clf = clone(model_instance)

        clf.fit(X_train_meta, y_train)


        oof_preds[val_idx] = clf.predict(X_val_meta)
        oof_probs[val_idx] = clf.predict_proba(X_val_meta)[:, 1]

    # 計算指標
    acc = accuracy_score(y, oof_preds)
    f1 = f1_score(y, oof_preds)
    auc = roc_auc_score(y, oof_probs)

    meta_performance[model_name] = {"Accuracy": acc, "F1-Score": f1, "AUC": auc}
    meta_oof_probs[model_name] = oof_probs

    print(f"--- {model_name} 詳細報告 ---")
    print(classification_report(y, oof_preds, target_names=['非業配 (F)', '業配文 (T)'], digits=3))

# =====================================================================
# 輸出最終模型報告 (字樣一併調整為 ROS)
# =====================================================================
print("\n=========================================================")
print("=============== ROS 後第二階段模型成效對比 ===============")
print("=========================================================")
perf_df = pd.DataFrame(meta_performance).T
print(perf_df.round(4))
print("=========================================================")

best_meta_model_name = perf_df['AUC'].idxmax()
print(f"\n 推薦使用【{best_meta_model_name}】")

"""## 重要特徵"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.rcdefaults()
sns.set_theme(style="whitegrid")

exclude_cols = ['id', 'title', 'content', '最終判定', 'label']
numerical_features = [col for col in labeled_df.columns if col not in exclude_cols]
X_meta = labeled_df[numerical_features].copy()
y = labeled_df['label'].values

feature_names = X_meta.columns

# =====================================================================
# 重跑一次最佳模型的 K-Fold，並沿途收集每一次的特徵重要性
# =====================================================================
n_splits = 5
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)
target_clf_template = meta_models[best_meta_model_name]

fold_importances = []

for fold, (train_idx, val_idx) in enumerate(skf.split(X_meta, y)):
    X_train_meta, y_train = X_meta.iloc[train_idx], y[train_idx]

    clf = clone(target_clf_template)
    clf.fit(X_train_meta, y_train)

    if "Logistic Regression" in best_meta_model_name:
        if hasattr(clf, 'named_steps'):
            coef = clf.named_steps['logisticregression'].coef_[0]
        else:
            coef = clf.coef_[0]
        fold_importances.append(coef)
    else:
        if hasattr(clf, 'named_steps'):
            importances = clf.named_steps['randomforestclassifier'].feature_importances_
        else:
            importances = clf.feature_importances_
        fold_importances.append(importances)

# =====================================================================
# 計算綜合平均後的特徵重要性
# =====================================================================
mean_importance = np.mean(fold_importances, axis=0)

if "Logistic Regression" in best_meta_model_name:
    importance_df = pd.DataFrame({
        'Feature': feature_names,
        'Importance': mean_importance,
        'Absolute_Importance': np.abs(mean_importance)
    }).sort_values(by='Absolute_Importance', ascending=False)
    title_text = f"Logistic Regression 5-Fold Mean Coefficients\nBest Model: {best_meta_model_name}"
    x_col = 'Importance'
else:
    importance_df = pd.DataFrame({
        'Feature': feature_names,
        'Importance': mean_importance
    }).sort_values(by='Importance', ascending=False)
    title_text = f"Tree-based Model 5-Fold Mean Feature Importance (Top 20)\nBest Model: {best_meta_model_name}"
    x_col = 'Importance'

# =====================================================================
# 視覺化
# =====================================================================
top_n = min(20, len(importance_df))
plt.figure(figsize=(12, 8))

if "Logistic Regression" in best_meta_model_name:
    colors = ['#ff4d4d' if val > 0 else '#33cc33' for val in importance_df[x_col].head(top_n)]
    sns.barplot(x=x_col, y='Feature', data=importance_df.head(top_n), palette=colors)
    plt.xlabel('Mean Coefficient Value (Positive: Pro-Sponsored / Negative: Anti-Sponsored)')
else:
    sns.barplot(x=x_col, y='Feature', data=importance_df.head(top_n), color='royalblue')
    plt.xlabel('Mean Feature Importance Score (Gini Importance)')

plt.title(title_text, fontsize=14, fontweight='bold')
plt.ylabel('Feature Name')
plt.grid(axis='x', linestyle='--', alpha=0.5)
plt.tight_layout()
plt.show()

# =====================================================================
# 文字輸出
# =====================================================================
print("\n===== 5-Fold Mean Feature Importance Top 15 Details =====")
for idx, (_, row) in enumerate(importance_df.head(15).iterrows()):
    if "Logistic Regression" in best_meta_model_name:
        relation = "[Positive (Pro-Sponsored)]" if row['Importance'] > 0 else "[Negative (Anti-Sponsored)]"
        print(f"Top {idx+1:<2}: {row['Feature']:<30} | Mean Coef: {row['Importance']:>7.4f} {relation}")
    else:
        print(f"Top {idx+1:<2}: {row['Feature']:<30} | Mean Importance: {row['Importance']:.4f}")